<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>LambdaConverters</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>LambdaConverters.Avalonia</PackageId>
A    <Version>11.3.0</Version>
    <Authors>Michael Damatov, Dimitri Enns, Alex Helms</Authors>
    <Description>The library allows to create IValueConverter and IMultiValueConverter objects with the most convenient syntax available, ideally, using the lambda expressions. This is an adaption of the LambdaConverters package for AvaloniaUI.</Description>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/alextnull/lambda-converters</PackageProjectUrl>
    <PackageIcon>Icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/alextnull/lambda-converters</RepositoryUrl>
    <PackageTags>lambda expression converter avalonia strongly typed value multi data template selector validation rule</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\Icon.png" Pack="True" PackagePath="" />
    <None Include="..\..\LICENSE" Pack="True" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.0" />
  </ItemGroup>

</Project>