<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>8.0</LangVersion>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>pdbonly</DebugType>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsAsErrors />
	</PropertyGroup>

	<Import Project="..\Tests.Shared\Tests.Shared.projitems" Label="Shared" />

	<ItemGroup>
		<ProjectReference Include="..\LambdaConverters.Avalonia\LambdaConverters.Avalonia.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="2.2.8" />
		<PackageReference Include="MSTest.TestFramework" Version="2.2.8" />
		<PackageReference Include="coverlet.collector" Version="3.1.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

</Project>
